// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I/usr/src/linux/include/uapi -I/usr/src/linux/include _types_msr_amd64.go

package isst

const (
	ISST_IF_MSR_COMMAND = 0xc008fe04
)

type MsrCmd struct {
	Read_write  uint32
	Logical_cpu uint32
	Msr         uint64
	Data        uint64
}
type MsrCmds struct {
	Cmd_count uint32
	Msr_cmd   [1]MsrCmd
}
