name: Trivy
on:
  workflow_call:
    inputs:
      upload-to-github-security-tab:
        default: false
        required: false
        type: boolean
      export-csv:
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  trivy-scan-licenses:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run Trivy in fs mode
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: fs
        scan-ref: .
        exit-code: 1
        scanners: license
        severity: "UNKNOWN,MEDIUM,HIGH,CRITICAL"

  trivy-scan-vulns:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run Trivy in fs mode
      continue-on-error: true
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: fs
        scan-ref: .
        exit-code: 1
        list-all-pkgs: true
        format: json
        output: trivy-report.json

    - name: Show report in human-readable format
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: convert
        vuln-type: ''
        severity: ''
        image-ref: trivy-report.json
        format: table

    - name: Convert report to sarif format
      if: ${{ inputs.upload-to-github-security-tab }}
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: convert
        vuln-type: ''
        severity: ''
        image-ref: trivy-report.json
        format: sarif
        output: trivy-report.sarif

    - name: Upload sarif report to GitHub Security tab
      if: ${{ inputs.upload-to-github-security-tab }}
      uses: github/codeql-action/upload-sarif@3d8036cf7fe7433e4a725cf513a6ea56c7fd0f14 # codeql-bundle-v2.25.0
      with:
       sarif_file: trivy-report.sarif

    - name: Convert report to csv
      if: ${{ inputs.export-csv }}
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        scan-type: convert
        vuln-type: ''
        severity: ''
        image-ref: trivy-report.json
        format: template
        template: "@.github/workflows/trivy-csv.tpl"
        output: trivy-report.csv

    - name: Upload CSV report as an artifact
      if: ${{ inputs.export-csv }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: trivy-report
        path: trivy-report.csv
